syntax on
set number

set mouse=a
set shiftwidth=4
set tabstop=4
set expandtab

set incsearch
set ignorecase
set smartcase
set showcmd
set showmode
set hlsearch
set history=1000

set wildmenu
set wildmode=list:longest

set number relativenumber

set paste

autocmd FileType gitcommit setlocal spell textwidth=72 colorcolumn=73
